server:
  port: 18081

spring:
  application:
    name: dubbo-consumer

dubbo:
  consumer:
    filter: tracing
  application:
    id: dubbo-consumer-demo
    name: dubbo-consumer-demo
  registry:
    id: my-registry
    address: zookeeper://devhost:8181

zipkin:
  tracing:
    endpoint: httpclient://devhost:8411/api/v2/spans
    kafka:
      bootstrap-servers: devhost:8093
      topic: zipkin
      overrides:
        security.protocol: SSL
        ssl.truststore.location: ${user.home}/kafka-jks/kafka-client-ts.jks
        ssl.truststore.password: client1234567
        ssl.keystore.location: ${user.home}/kafka-jks/kafka-client-ks.jks
        ssl.keystore.password: client1234567
        ssl.key.password: client1234567
