server:
  port: 18081

spring:
  application:
    name: dubbo-consumer

dubbo:
  consumer:
    filter: tracing
  application:
    id: dubbo-consumer-demo
    name: dubbo-consumer-demo
  registry:
    id: my-registry
    address: zookeeper://devhost:8181

zipkin:
  tracing:
    endpoint: http://devhost:8411/api/v2/spans
    kafka:
      bootstrap-servers: devhost:8092
      topic: zipkin
