server:
  port: 18082

spring:
  application:
    name: dubbo-provider

dubbo:
  provider:
    filter: tracing
  scan:
    basePackages: org.example.dubbo.service
  application:
    id: dubbo-provider-demo
    name: dubbo-provider-demo
  protocol:
    id: dubbo
    name: dubbo
    port: 12345
  registry:
    id: my-registry
    address: zookeeper://devhost:8181

zipkin:
  tracing:
    endpoint: http://devhost:8411/api/v2/spans
    kafka:
      bootstrap-servers: devhost:8092
      topic: zipkin
