server:
  port: 18080

spring:
  application:
    name: dubbo-web

zipkin:
  tracing:
    endpoint: httpclient://localhost:9411/api/v2/spans
    kafka:
      bootstrap-servers: localhost:9093
      topic: zipkin
      overrides:
        security.protocol: SSL
        ssl.truststore.location: ${user.home}/kafka-jks/kafka-client-ts.jks
        ssl.truststore.password: client1234567
        ssl.keystore.location: ${user.home}/kafka-jks/kafka-client-ks.jks
        ssl.keystore.password: client1234567
        ssl.key.password: client1234567

logging:
  level: debug

debug: true
