server:
  port: 18080

spring:
  application:
    name: dubbo-web

zipkin:
  tracing:
    endpoint: http://devhost:8411/api/v2/spans
    kafka:
      bootstrap-servers: devhost:8092
      topic: zipkin
